### ISSUE TITLE
ImportError: cannot import name 'Directive'

### ISSUE THREAD

**Issue by suvarchal** [pyviz/nbsite#50] opened 2018-05-23 15:40 UTC
this issue prevents me making docs with nbsite, for testing i cloned geoviews which seems to be using nbsite for its docs. 

> cd doc
> sphinx-build . _build

Raises error

> Configuration error:
> There is a programable error in your configuration file:
> 
> Traceback (most recent call last):
>   File "/home/user/miniconda3/lib/python3.6/site-packages/sphinx/config.py", line 161, in __init__
>     execfile_(filename, config)
>   File "/home/user/miniconda3/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
>     exec_(code, _globals)
>   File "conf.py", line 3, in <module>
>     from nbsite.shared_conf import *
>   File "/home/user/miniconda3/lib/python3.6/site-packages/nbsite/shared_conf.py", line 5, in <module>
>     from nbsite import nbbuild
>   File "/home/user/miniconda3/lib/python3.6/site-packages/nbsite/nbbuild.py", line 30, in <module>
>     from sphinx.util.compat import Directive
> ImportError: cannot import name 'Directive'
> 

My sphinx version is 1.7.4 , on googling it i also found someone else [has it](https://github.com/spinus/sphinxcontrib-images/issues/4).

**Comment by ceball** [comment] 2018-05-23 21:04
Yes, sorry for the trouble. However, this issue is a duplicate of #35.

**Closed by ceball** 2018-05-23 21:04 UTC
Labels: bug
